#!/usr/bin/env bash
# ==========================================================================
# setapi.sh — bootstrap all per-app .env.local files with the real dev
# credentials, in one shot, after a fresh clone.
#
#   ⚠️  THIS FILE CONTAINS SECRETS. It is gitignored (see .gitignore).
#       NEVER commit it, never push it to GitHub, never paste it anywhere.
#
# Usage (from repo root):   bash setapi.sh    (or: chmod +x setapi.sh && ./setapi.sh)
#
# It OVERWRITES the three .env.local files with the values below. Edit the
# values here (not the generated files) so this stays the single source.
# For PRODUCTION: rotate every secret, set COOKIE_SECURE=true, use real
# domains in CORS_ORIGINS / NEXT_PUBLIC_* , and a strong ADMIN_PASSWORD.
# ==========================================================================
set -euo pipefail
cd "$(dirname "$0")"

# ---------------------------------------------------------------- apps/api
cat > apps/api/.env.local <<'EOF'
# RANGAMAI API — LOCAL DEV SECRETS. Gitignored. Generated by setapi.sh.

PORT=4000
# MongoDB Atlas. Password had an "@" so it's URL-encoded (@ -> %40).
# Offline fallback: MONGODB_URI=mongodb://127.0.0.1:27017/rangamai
MONGODB_URI=mongodb+srv://anger:Radha%40123@rangamdbfree.xhhxr3g.mongodb.net/rangamai?retryWrites=true&w=majority&appName=rangamDBFREE

# Auth
JWT_SECRET=u2Jbvduws--NBu_8HvdduaLa42f3ywYT35k23vJG53LucG_0k_VuLGbt2BsP_g7h
JWT_EXPIRES_IN=1d
COOKIE_SECURE=false
COOKIE_NAME=rangamai_token

# CORS — public site + admin dashboard
CORS_ORIGINS=http://localhost:3000,http://localhost:3001

# Seed admin (change the password before any real deployment)
ADMIN_EMAIL=admin@rangamai.in
ADMIN_PASSWORD=ChangeMe!Dev12345
ADMIN_NAME=RANGAMAI Admin

# Cloudinary (real keys — gitignored, never commit)
CLOUDINARY_CLOUD_NAME=lukaemhr
CLOUDINARY_API_KEY=538597584168569
CLOUDINARY_API_SECRET=mE8cIbyUkWfByCmUjV8ItI7oEpo
CLOUDINARY_FOLDER=rangamai
EOF

# ---------------------------------------------------------------- apps/web
cat > apps/web/.env.local <<'EOF'
# RANGAMAI public site — local dev. Gitignored. Generated by setapi.sh.
NEXT_PUBLIC_SITE_URL=http://localhost:3000
NEXT_PUBLIC_API_URL=http://localhost:4000
EOF

# -------------------------------------------------------------- apps/admin
cat > apps/admin/.env.local <<'EOF'
# RANGAMAI admin dashboard — local dev. Gitignored. Generated by setapi.sh.
NEXT_PUBLIC_API_URL=http://localhost:4000
NEXT_PUBLIC_SITE_URL=http://localhost:3000
EOF

echo "✅ Wrote .env.local for: apps/api, apps/web, apps/admin"
echo "   Next: npm install && npm run seed && npm run app"
